<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Perpustakaan;

class PerpustakaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Perpustakaan::truncate();

        $koleksi = [
            [
                'judul' => 'Undang-Undang Nomor 20 Tahun 2023 tentang Aparatur Sipil Negara',
                'nomor_dokumen' => 'UU No. 20 Tahun 2023',
                'kategori' => 'Regulasi',
                'penulis' => 'Pemerintah Republik Indonesia & DPR RI',
                'penerbit' => 'Kementerian Sekretariat Negara RI',
                'tahun' => 2023,
                'deskripsi' => 'Landasan hukum utama penguatan profesionalisme, digitalisasi manajemen ASN, mobilitas talenta nasional, dan penataan tenaga non-ASN di Indonesia.',
                'file_format' => 'PDF',
                'file_size' => '3.8 MB',
                'jumlah_halaman' => 86,
                'jumlah_unduh' => 420,
                'is_featured' => true,
                'cover_color' => 'blue',
            ],
            [
                'judul' => 'Peraturan Pemerintah Nomor 94 Tahun 2021 tentang Disiplin Pegawai Negeri Sipil',
                'nomor_dokumen' => 'PP No. 94 Tahun 2021',
                'kategori' => 'Regulasi',
                'penulis' => 'Presiden Republik Indonesia',
                'penerbit' => 'Kementerian Sekretariat Negara RI',
                'tahun' => 2021,
                'deskripsi' => 'Pedoman kewajiban, larangan, jenis sanksi hukuman disiplin ASN, dan tata cara pemeriksaan serta penjatuhan hukuman disiplin.',
                'file_format' => 'PDF',
                'file_size' => '2.1 MB',
                'jumlah_halaman' => 45,
                'jumlah_unduh' => 285,
                'is_featured' => false,
                'cover_color' => 'rose',
            ],
            [
                'judul' => 'PermenPAN-RB Nomor 1 Tahun 2023 tentang Jabatan Fungsional',
                'nomor_dokumen' => 'PermenPAN-RB No. 1 Th 2023',
                'kategori' => 'Regulasi',
                'penulis' => 'Menteri PAN-RB',
                'penerbit' => 'KemenPAN-RB',
                'tahun' => 2023,
                'deskripsi' => 'Transformasi tata kelola Jabatan Fungsional berbasis ekspektasi kinerja dan integrasi angka kredit ke dalam konversi predikat SKP.',
                'file_format' => 'PDF',
                'file_size' => '4.2 MB',
                'jumlah_halaman' => 64,
                'jumlah_unduh' => 312,
                'is_featured' => true,
                'cover_color' => 'purple',
            ],
            [
                'judul' => 'Peraturan BKN Nomor 3 Tahun 2023 tentang Tata Cara Periodesasi Kenaikan Pangkat PNS',
                'nomor_dokumen' => 'Perka BKN No. 3 Th 2023',
                'kategori' => 'Regulasi',
                'penulis' => 'Badan Kepegawaian Negara',
                'penerbit' => 'BKN RI',
                'tahun' => 2023,
                'deskripsi' => 'Ketentuan kenaikan pangkat PNS menjadi 6 periode setiap tahun (Februari, April, Juni, Agustus, Oktober, Desember).',
                'file_format' => 'PDF',
                'file_size' => '1.9 MB',
                'jumlah_halaman' => 32,
                'jumlah_unduh' => 390,
                'is_featured' => true,
                'cover_color' => 'emerald',
            ],
            [
                'judul' => 'Modul Pelatihan Dasar (Latsar) CPNS: Core Values ASN BerAKHLAK',
                'nomor_dokumen' => 'MOD-LAN-2022-01',
                'kategori' => 'Modul Diklat',
                'penulis' => 'Lembaga Administrasi Negara (LAN RI)',
                'penerbit' => 'LAN Press',
                'tahun' => 2022,
                'deskripsi' => 'Modul internalisasi nilai-nilai dasar Berorientasi Pelayanan, Akuntabel, Kompeten, Harmonis, Loyal, Adaptif, dan Kolaboratif bagi seluruh ASN.',
                'file_format' => 'PDF',
                'file_size' => '5.6 MB',
                'jumlah_halaman' => 120,
                'jumlah_unduh' => 510,
                'is_featured' => true,
                'cover_color' => 'amber',
            ],
            [
                'judul' => 'Pedoman Pelatihan Kepemimpinan Administrator (PKA): Manajemen Kinerja Sektor Publik',
                'nomor_dokumen' => 'PKA-LAN-2023',
                'kategori' => 'Modul Diklat',
                'penulis' => 'Puslatbang PKASN LAN RI',
                'penerbit' => 'LAN RI',
                'tahun' => 2023,
                'deskripsi' => 'Panduan penyusunan rancangan aksi perubahan dan strategi kepemimpinan kinerja organisasi di instansi pemerintah daerah.',
                'file_format' => 'PDF',
                'file_size' => '7.1 MB',
                'jumlah_halaman' => 158,
                'jumlah_unduh' => 174,
                'is_featured' => false,
                'cover_color' => 'blue',
            ],
            [
                'judul' => 'SOP Pengusulan Kenaikan Gaji Berkala (KGB) Otomatis Berbasis SIMPEG',
                'nomor_dokumen' => 'SOP/BKPSDM/2024/008',
                'kategori' => 'SOP Layanan',
                'penulis' => 'Bidang Mutasi dan Kepangkatan',
                'penerbit' => 'BKPSDM Kabupaten Bandung',
                'tahun' => 2024,
                'deskripsi' => 'Standar Operasional Prosedur verifikasi dan penerbitan Surat Keputusan Kenaikan Gaji Berkala bagi PNS dan PPPK.',
                'file_format' => 'PDF',
                'file_size' => '1.1 MB',
                'jumlah_halaman' => 18,
                'jumlah_unduh' => 230,
                'is_featured' => false,
                'cover_color' => 'emerald',
            ],
            [
                'judul' => 'SOP Pemberian Rekomendasi Tugas Belajar dan Izin Belajar ASN',
                'nomor_dokumen' => 'SOP/BKPSDM/2024/014',
                'kategori' => 'SOP Layanan',
                'penulis' => 'Bidang Pengembangan Kompetensi',
                'penerbit' => 'BKPSDM Kabupaten Bandung',
                'tahun' => 2024,
                'deskripsi' => 'Tahapan pengajuan, seleksi administrasi, uji kelayakan, dan penetapan surat keputusan izin/tugas belajar pegawai.',
                'file_format' => 'PDF',
                'file_size' => '1.4 MB',
                'jumlah_halaman' => 22,
                'jumlah_unduh' => 195,
                'is_featured' => false,
                'cover_color' => 'rose',
            ],
            [
                'judul' => 'Jurnal Kebijakan dan Manajemen Kepegawaian: Analisis Kesiapan Transformasi Digital ASN',
                'nomor_dokumen' => 'ISSN 1978-7162 / Vol. 18 No. 2',
                'kategori' => 'Jurnal',
                'penulis' => 'Pusat Riset dan Inovasi Manajemen ASN BKN',
                'penerbit' => 'BKN Publishing',
                'tahun' => 2024,
                'deskripsi' => 'Kajian empiris mengenai adaptabilitas aparatur sipil negara terhadap integrasi SIASN, E-Kinerja, dan pemanfaatan AI dalam pelayanan publik.',
                'file_format' => 'PDF',
                'file_size' => '3.1 MB',
                'jumlah_halaman' => 52,
                'jumlah_unduh' => 140,
                'is_featured' => false,
                'cover_color' => 'purple',
            ],
            [
                'judul' => 'E-Book: Kamus Kompetensi Teknis Urusan Pemerintahan Daerah',
                'nomor_dokumen' => 'ISBN 978-623-001-2',
                'kategori' => 'E-Book',
                'penulis' => 'Tim Pengembang Standar Kompetensi ASN Kemendagri & BKN',
                'penerbit' => 'Kemendagri Press',
                'tahun' => 2023,
                'deskripsi' => 'Referensi komprehensif indikator perilaku dan level kecakapan kompetensi teknis ASN pada setiap jenjang jabatan pemerintah daerah.',
                'file_format' => 'PDF',
                'file_size' => '8.4 MB',
                'jumlah_halaman' => 240,
                'jumlah_unduh' => 365,
                'is_featured' => true,
                'cover_color' => 'amber',
            ],
            [
                'judul' => 'Petunjuk Teknis Pengelolaan Kinerja Pegawai pada Aplikasi SIASN BKN',
                'nomor_dokumen' => 'JUKNIS-BKN-2024-03',
                'kategori' => 'Modul Diklat',
                'penulis' => 'Direktorat Kinerja ASN BKN',
                'penerbit' => 'BKN RI',
                'tahun' => 2024,
                'deskripsi' => 'Panduan langkah demi langkah pengisian SKP, evaluasi periodik triwulan, feedback perilaku, dan penetapan predikat kinerja final.',
                'file_format' => 'PDF',
                'file_size' => '4.8 MB',
                'jumlah_halaman' => 74,
                'jumlah_unduh' => 450,
                'is_featured' => false,
                'cover_color' => 'blue',
            ],
            [
                'judul' => 'SOP Layanan Mutasi dan Penempatan Kembali Pegawai Antar OPD',
                'nomor_dokumen' => 'SOP/BKPSDM/2024/005',
                'kategori' => 'SOP Layanan',
                'penulis' => 'Bidang Pengadaan, Pemberhentian dan Informasi',
                'penerbit' => 'BKPSDM Kabupaten Bandung',
                'tahun' => 2024,
                'deskripsi' => 'Standar operasional prosedur pengajuan mutasi internal berorientasi pada analisis jabatan dan beban kerja (Anjab-ABK).',
                'file_format' => 'PDF',
                'file_size' => '1.2 MB',
                'jumlah_halaman' => 16,
                'jumlah_unduh' => 180,
                'is_featured' => false,
                'cover_color' => 'emerald',
            ]
        ];

        foreach ($koleksi as $item) {
            Perpustakaan::create($item);
        }
    }
}
